# Generated by Django 4.0.4 on 2022-04-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_cat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='user',
        ),
    ]
